### ISSUE TITLE
[Feature]: Add the issue, bug, Pull request and feature template for contributors

### ISSUE THREAD

**Issue by praptisharma28** [tushar5526/sarthi#32]
This will help the maintainer keep the track of all the contributors.

**Comment by praptisharma28** [comment]
Assign me @tushar5526 under iwoc

**Comment by tushar5526** [comment]
Go ahead!

**Comment by praptisharma28** [comment]
@tushar5526 put the iwoc tag too

**Comment by tushar5526** [comment]
HI @praptisharma28 - I think easy is quite suitable for it. There are other issues with higher difficulty that you can contribute to and learn as well.

**Comment by praptisharma28** [comment]
@tushar5526 please check, thanks.

**Comment by praptisharma28** [comment]
@tushar5526 the program ends today, please merge it.
